version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_NAME}

  redis:
    container_name: redis
    image: redis:alpine

  central:
    container_name: central
    restart: on-failure
    build:
      context: ./central
      dockerfile: Dockerfile
    volumes:
      - ./central:/central
    environment:
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - STREAM_KEY=${STREAM_KEY}
      - API_URI=${API_URI}
    command: python main.py
    depends_on:
      - redis
      - lineman

  lineman:
    container_name: lineman
    restart: on-failure
    build:
      context: ./lineman
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./lineman:/lineman
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_DB=${POSTGRES_NAME}
      - DATABASE_NAME=${DATABASE_NAME}
    command: flask --app app run --host=0.0.0.0
    stop_signal: SIGINT
    depends_on:
      - postgres

  celery:
    build:
      context: ./train
      dockerfile: Dockerfile
    command: celery -A main.app worker -l INFO
    restart: on-failure
    volumes:
      - ./train:/train
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  train:
    build:
      context: ./train
      dockerfile: Dockerfile
    command: celery -A main.app beat -l INFO
    environment:
      - REDIS_HOST_NAME=${REDIS_HOST_NAME}
      - REDIS_PORT=${REDIS_PORT}
      - STREAM_KEY=${STREAM_KEY}
    volumes:
      - ./train:/train
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
